# Generated by Django 4.1.7 on 2023-03-08 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studmanageapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll_num',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField()),
                ('roll_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studmanageapp.student')),
            ],
        ),
    ]
